# Generated by Django 3.1.6 on 2021-02-11 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='adress',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='institution.adress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='contact',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='institution.contact'),
            preserve_default=False,
        ),
    ]
