# Generated by Django 3.1.6 on 2021-02-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20210211_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adress_name',
            new_name='address_name',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='adress',
            new_name='address',
        ),
    ]
